[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-core"
  [plugins.inputs]
    node_bundler = "esbuild"
    external_node_modules = ["faunadb"]

# 共有URLのパスパターンを処理するためのリダイレクトルール
[[redirects]]
  from = "/s/*"
  to = "/index.html"
  status = 200
  force = true

# その他のすべてのパスをindex.htmlにリダイレクト
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"

[context.production.environment]
  GO_VERSION = "1.19"
