[build]
  command = "npm run build"
  publish = "dist"

# 共有URLのパスパターンを処理するためのリダイレクトルール
[[redirects]]
  from = "/s/*"
  to = "/index.html"
  status = 200
  force = true

# その他のすべてのパスをindex.htmlにリダイレクト
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"