// ヘッダーの定義を配列で順序を保証
export const EXCEL_HEADER_ORDER = [
  'date',
  'dayOfWeek', 
  'period',
  'class1A_subject',
  'class1A_teacher',
  'class1A_duration',
  'class1B_subject',
  'class1B_teacher',
  'class1B_duration',
  'class1N_subject',
  'class1N_teacher',
  'class1N_duration',
  'class2A_subject',
  'class2A_teacher',
  'class2A_duration',
  'class2B_subject',
  'class2B_teacher',
  'class2B_duration',
  'class2N_subject',
  'class2N_teacher',
  'class2N_duration',
  'class3A_subject',
  'class3A_teacher',
  'class3A_duration',
  'class3B_subject',
  'class3B_teacher',
  'class3B_duration',
  'class3N_subject',
  'class3N_teacher',
  'class3N_duration',
  'class3_exam'
] as const;

// ヘッダーの日本語表示名
export const EXCEL_HEADERS = {
  date: '日付',
  dayOfWeek: '曜日',
  period: '時限',
  // 1年
  class1A_subject: '1年A組の授業内容',
  class1A_teacher: '1年A組担当講師名',
  class1A_duration: '1年A組コマ数',
  class1B_subject: '1年B組の授業内容',
  class1B_teacher: '1年B組担当講師名',
  class1B_duration: '1年B組コマ数',
  class1N_subject: '1年N組の授業内容',
  class1N_teacher: '1年N組担当講師名',
  class1N_duration: '1年N組コマ数',
  // 2年
  class2A_subject: '2年A組の授業内容',
  class2A_teacher: '2年A組担当講師名',
  class2A_duration: '2年A組コマ数',
  class2B_subject: '2年B組の授業内容',
  class2B_teacher: '2年B組担当講師名',
  class2B_duration: '2年B組コマ数',
  class2N_subject: '2年N組の授業内容',
  class2N_teacher: '2年N組担当講師名',
  class2N_duration: '2年N組コマ数',
  // 3年
  class3A_subject: '3年A組の授業内容',
  class3A_teacher: '3年A組担当講師名',
  class3A_duration: '3年A組コマ数',
  class3B_subject: '3年B組の授業内容',
  class3B_teacher: '3年B組担当講師名',
  class3B_duration: '3年B組コマ数',
  class3N_subject: '3年N組の授業内容',
  class3N_teacher: '3年N組担当講師名',
  class3N_duration: '3年N組コマ数',
  class3_exam: '3年各種模擬試験'
} as const;